import { GoogleOAuthProvider } from '@react-oauth/google'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import { Header } from '@/shared/components/layout/header'
import { ThemeProvider } from '@/shared/components/theme-provider'

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-noto-sans-kr',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ''
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${notoSansKR.className} antialiased`}>
        <GoogleOAuthProvider clientId={googleClientId}>
          <ThemeProvider>
            <div className="min-w-5xl mt-14">
              <Header />
              {children}
            </div>
          </ThemeProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
